### ISSUE TITLE
Hyperion status on restart

### ISSUE THREAD

**Issue by YellowNest** [satrik/homebridge-hyperion-control#1]
I dont know if this has anything to do with the plugin or not but I have the following issue...

When I restart my pi, Hyperion.ng starts ambilight aswell. Homekit doesnt seem to get the information so it sees everything as off by default. Is there a way to make the plugin get that information during startup?

**Comment by satrik** [comment]
The plugin should fetch the current state every time you open the Home App.

Are you using the same Pi for Hyperion and Homebridge?
Is the device in Homebridge also off?
Have you tried to quit and reopen the Home App?
