### ISSUE TITLE
Features from other forks

### ISSUE THREAD

**Issue by mitch7391** [satrik/homebridge-hyperion-control#4]
Hey @satrik for the short time I could not install this plugin due to the node-fetch PR issue; I had noticed there was another fork that seems to have added some other features. Looking through the commit history it was a lot of trial and error. But do you think there is anything of value you can transfer over from that fork? I believe they have added the hue characteristic as one of the features.

https://github.com/cortl/homebridge-hyperion-control

No pressure and just a thought :)

**Comment by satrik** [comment]
Hey @mitch7391 I actually wanted to rewrite the whole plugin at some point 😄 if I find the time, I add colors (hue)

**Comment by mitch7391** [comment]
Sounds awesome @satrik!

**Comment by mitch7391** [comment]
@satrik have you heard of [HyperHDR](https://github.com/awawa-dev/HyperHDR)? I have been testing it out recently and appears to have begun as a fork from Hyperion that supports proper HDR processing and I have noticed it mostly works with this plugin. I think there are some issues with the 'get' status of the switch at time but otherwise the switch issues an off/on for that project. Could be worth checking out and thought I would let you know.

**Comment by satrik** [comment]
@mitch7391 a few days ago I installed HyperHDR and it is amazing. I also changed a lot of my setup and I'm not sure if I need this plugin in the future 😐
I use now WLED to control the LEDs - hyperion can handle WLED OOTB without any noticeable delay. therefore I don't have any need for this plugin currently...

**Comment by mitch7391** [comment]
@satrik I am glad to have passed on the info about HyperHDR then! It is a bit of a bugger that you will no longer be invested this plug-in though. I have still been able to use this plug-in with HyperHDR; it just have its occasional hiccups but is still functional enough in the basic form of turning it off and on.
