### ISSUE TITLE
TV screen streaming via camera accessory

### ISSUE THREAD

**Issue by sergoo-lbt** [satrik/homebridge-hyperion-control#5]
I wonder if it is possible to broadcast a picture from the hyperion grabber to homekit via a camera accessory? It would be cool to remotely watch what the kids are watching while I'm not at home!👍🏻😅

**Comment by satrik** [comment]
sorry for the late response. don't think this is possible without "more" work. you could try the forwarder function from hyperion to send the video to any local script which makes a http/rtsp stream of it and this stream could be used with a http camera plugin for homebridge.
but I have no use case and no time for such a feature ^^
